# FONTS
font_family CaskaydiaCove Nerd Font
font_size   12


# CURSOR
cursor_shape           beam
cursor_shape_unfocused beam
cursor_beam_thickness  1
cursor_blink_interval  0.5 ease-in-out
cursor_trail 1


# WINDOW
window_padding_width    6 0 0 8
confirm_os_window_close 0


# COLOR SCHEME
background_opacity 0.8
background_blur    1
